import turtle
turtle.showturtle()
turtle.forward(200)
turtle.penup()
turtle.right(180)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(180)
turtle.pendown()
turtle.forward(200)
turtle.done()
