import turtle

turtle.penup()
turtle.right(90)
turtle.forward(100)
turtle.left(90)
turtle.pendown()
turtle.circle(100)
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.forward(70)
turtle.goto(0,0)
turtle.right(180)
turtle.forward(50)
turtle.goto(0,0)
turtle.right(90)
turtle.forward(85)

turtle.penup()
turtle.goto(93,-5)
turtle.write(3)
turtle.goto(-5,85)
turtle.write(12)
turtle.goto(-95,-5)
turtle.write(9)
turtle.goto(0,-98)
turtle.write(6)

turtle.goto(-10,-115)
turtle.write("9:15:00")
turtle.hideturtle()
turtle.done()